name: Setup
runs:
  using: 'composite'
  steps:
    - name: Install Node.js 18.x
      uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # tag=v2
      with:
        node-version: 18.x
        cache: npm
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      env:
        CI: true
      shell: bash
      run: |
        yarn install
