services:
  postgres:
    image: postgres:15.6-alpine
    environment:
      POSTGRES_DB: 'sleepymaid'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sleepymaid']
      interval: 10s
      timeout: 5s

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 10s
      timeout: 5s

  ghost:
    image: ghost:5-alpine
    restart: unless-stopped
    expose:
      - 2368
    ports:
      - '2368:2368'
    environment:
      url: 'https://blog.ecorte.xyz'
      database__client: 'sqlite3'
      database__connection__filename: '/var/lib/ghost/content/data/ghost.db'
      mail__transport: 'SMTP'
      mail__options__service: 'Mailgun'
    volumes:
      - ghost-data:/var/lib/ghost/content

  #api:
  #  build:
  #    context: ../
  #    dockerfile: ./docker/api/Dockerfile
  #  restart: unless-stopped
  #  expose:
  #    - 8080
  #  environment:
  #    DATABASE_URL: 'postgresql://sleepymaid:admin@postgres:5432/sleepymaid'
  #    REDIS_URL: 'redis://redis:6379/0'

  sleepymaid:
    container_name: sleepymaid_sleepymaid
    build:
      context: ../
      dockerfile: ./docker/services/Dockerfile
    command: node --trace-warnings -r source-map-support/register services/sleepymaid/dist/index.js
    restart: unless-stopped
    depends_on:
      - 'postgres'
      - 'redis'

  helper:
    container_name: sleepymaid_helper
    build:
      context: ../
      dockerfile: ./docker/services/Dockerfile
    command: node --trace-warnings -r source-map-support/register services/helper/dist/index.js
    restart: unless-stopped
    depends_on:
      - 'postgres'
      - 'redis'

  watcher:
    container_name: sleepymaid_watcher
    build:
      context: ../
      dockerfile: ./docker/services/Dockerfile
    command: node --trace-warnings -r source-map-support/register services/watcher/dist/index.js
    restart: unless-stopped
    depends_on:
      - 'postgres'
      - 'redis'

  #website:
  #  build:
  #    context: ../
  #    dockerfile: ./docker/website/Dockerfile
  #    args:
  #      NEXT_PUBLIC_CLIENTVAR: 'clientvar'
  #  restart: unless-stopped
  #  expose:
  #    - 3000
  #  ports:
  #    - '3000:3000'
  #  environment:
  #    DATABASE_URL: 'postgresql://sleepymaid:admin@postgres:5432/sleepymaid'
  #    REDIS_URL: 'redis://redis:6379/0'
  #    NEXTAUTH_URL: 'http://localhost:3000'

  zipline:
    image: ghcr.io/diced/zipline
    ports:
      - '3002:3002'
    restart: unless-stopped
    environment:
      - CORE_RETURN_HTTPS=false
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3002
      - CORE_LOGGER=true
    volumes:
      - './uploads:/zipline/uploads'
      - './public:/zipline/public'
    depends_on:
      - 'postgres'

  cobalt-api:
    image: ghcr.io/wukko/cobalt:7
    restart: unless-stopped
    container_name: cobalt-api

    init: true

    # if container doesn't run detached on your machine, uncomment the next line
    #tty: true

    ports:
      #- 9000:9000/tcp
      # if you're using a reverse proxy, uncomment the next line and remove the one above (9000:9000/tcp):
      - 127.0.0.1:9000:9000

    environment:
      # replace https://co.wuk.sh/ with your instance's target url in same format
      API_URL: 'https://cobaltapi.ecorte.xyz/'
      # replace eu-nl with your instance's distinctive name
      API_NAME: 'us4'
      # see docs/run-an-instance.md for more information
      COOKIE_PATH: '/cookies.json'
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt

    # if you want to use cookies when fetching data from services, uncomment volumes and next line
    volumes:
      - ./cookies.json:/cookies.json

  cobalt-web:
    image: ghcr.io/wukko/cobalt:7
    restart: unless-stopped
    container_name: cobalt-web

    init: true

    # if container doesn't run detached on your machine, uncomment the next line
    #tty: true

    ports:
      #- 9001:9001/tcp
      # if you're using a reverse proxy, uncomment the next line and remove the one above (9001:9001/tcp):
      - 127.0.0.1:9001:9001

    environment:
      # replace https://cobalt.tools/ with your instance's target url in same format
      WEB_URL: 'https://cobalt.ecorte.xyz/'
      # replace https://co.wuk.sh/ with preferred api instance url
      API_URL: 'https://coapi.ecorte.xyz/'

    labels:
      - com.centurylinklabs.watchtower.scope=cobalt

  # update the cobalt image automatically with watchtower
  watchtower:
    image: ghcr.io/containrrr/watchtower
    restart: unless-stopped
    command: --cleanup --scope cobalt --interval 900
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis-data:
    name: 'sleepymaid-redis-data'
    external: true
  postgres-data:
    name: 'sleepymaid-postgres-data'
    external: true
  ghost-data:
    name: 'sleepymaid-ghost-data'
    external: true
